services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gzouli-backend
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${GZOULI_DB_USER}
      - DB_PASSWORD=${GZOULI_DB_PASSWORD}
      - DB_NAME=${GZOULI_DB_NAME}
      - SPRING_PROFILES_ACTIVE=docker
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_COGNITO_USER_POOL_ID=${AWS_COGNITO_USER_POOL_ID}
      - AWS_COGNITO_APP_CLIENT_ID=${AWS_COGNITO_APP_CLIENT_ID}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - NVD_API_KEY=${NVD_API_KEY}
    depends_on:
      db :
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 20s
    networks:
      - gzouli_erp

  db:
    image: postgres:16
    container_name: gzouli-bdd
    restart: always
    environment:
      POSTGRES_DB: ${GZOULI_DB_NAME}
      POSTGRES_USER: ${GZOULI_DB_USER}
      POSTGRES_PASSWORD: ${GZOULI_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${GZOULI_DB_USER} -d ${GZOULI_DB_NAME}" ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - gzouli_erp

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gzouli-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - gzouli_erp

volumes:
  db-data:

networks:
  gzouli_erp:
    driver: bridge