apiVersion: apps/v1
kind: Deployment
metadata:
  name: gzouli-db-deploy
  namespace: gzouli-dev
  labels:
    app: gzouli-db-deploy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gzouli-db
  template:
    metadata:
      labels:
        app: gzouli-db
    spec:
      containers:
        - name: gzouli-db-container
          image: postgres:16
          ports:
            - containerPort: 5432
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: gzouli-db-cm
            - secretRef:
                name: gzouli-db-secret
          startupProbe:
            exec:
              command: [ "sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
            periodSeconds: 5
            failureThreshold: 12
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: [ "sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: [ "sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
            periodSeconds: 20
            failureThreshold: 6
            timeoutSeconds: 5