apiVersion: v1
kind: Secret
metadata:
  name: gzouli-db-secret
  namespace: gzouli-dev
  labels:
    app: gzouli-db-secret-label-app
stringData:
  POSTGRES_USER: "test-db-user"
  POSTGRES_PASSWORD: "test-db-password"