spring:
  application:
    name: ERP
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.${AWS_REGION}.amazonaws.com/${AWS_COGNITO_USER_POOL_ID}

aws:
  region: ${AWS_REGION}
  s3:
    bucketName: ${AWS_S3_BUCKET_NAME}
  cognito:
    userPoolId: ${AWS_COGNITO_USER_POOL_ID}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO